try
	x=0
catch as error
	throw error
